# Generated by Django 4.2.30 on 2026-06-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_bank',
            field=models.BooleanField(default=False),
        ),
    ]
